### ISSUE TITLE
How to collect high frequence leica measurement

### ISSUE THREAD

**Issue by dysenustc** [uzh-rpg/ICRA2020-FPV-VIO-Competition#2]
I want to know how to record high frequence(up to 20Hz) leica position measurement.
my ms60 only can record up to 10Hz measurement using Leica Captivate, and the maximum dt reach 700ms betwween two continuous measurements in one of my collect data.

**Comment by tcies** [comment]
I don't have a quick answer to this, as I wasn't directly involved, sorry, would need to do some digging. It's on my to do list, but I cannot make any promises...

**Comment by tcies** [comment]
Replied via email.
